# Generated by Django 3.0.8 on 2020-09-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='poll',
        ),
    ]
